// <auto-generated />
using System;
using HastaneApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HastaneApi.Migrations
{
    [DbContext(typeof(HastaneDbContext))]
    [Migration("20240125113522_mig1")]
    partial class mig1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HastaneApi.Entities.Hasta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HastaneId")
                        .HasColumnType("int");

                    b.Property<string>("Klinik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MuayeneTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HastaneId");

                    b.ToTable("Hastalar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "aaa",
                            HastaneId = 1,
                            Klinik = "kbb",
                            MuayeneTarihi = new DateTime(2024, 1, 25, 14, 35, 22, 159, DateTimeKind.Local).AddTicks(8542),
                            Soyad = "bbb"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "ccc",
                            HastaneId = 2,
                            Klinik = "ortopedi",
                            MuayeneTarihi = new DateTime(2024, 1, 25, 14, 35, 22, 159, DateTimeKind.Local).AddTicks(8551),
                            Soyad = "ddd"
                        });
                });

            modelBuilder.Entity("HastaneApi.Entities.Hastane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("HastaneAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HastaneAdres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hastaneler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HastaneAd = "Academic",
                            HastaneAdres = "Uskudar"
                        },
                        new
                        {
                            Id = 2,
                            HastaneAd = "Acıbadem",
                            HastaneAdres = "kadıkoy"
                        });
                });

            modelBuilder.Entity("HastaneApi.Entities.Hasta", b =>
                {
                    b.HasOne("HastaneApi.Entities.Hastane", "Hastane")
                        .WithMany("Hastalar")
                        .HasForeignKey("HastaneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hastane");
                });

            modelBuilder.Entity("HastaneApi.Entities.Hastane", b =>
                {
                    b.Navigation("Hastalar");
                });
#pragma warning restore 612, 618
        }
    }
}
